/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const headers_OnRead = require('./code/headers-onRead');

class Smart_Invoice_AppService extends LCAPApplicationService {
    async init() {

        this.after('READ', 'Headers', async (results, request) => {
            await headers_OnRead(results, request);
        });

        return super.init();
    }
}


module.exports = {
    Smart_Invoice_AppService
};